# Generated by Django 4.2 on 2024-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipi', '0003_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefield',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
