# Generated by Django 4.2 on 2024-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipi', '0006_remove_extrafield_index_remove_extrafield_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefield',
            name='field_value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
