# Generated by Django 4.2 on 2024-10-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipi', '0007_imagefield_field_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('your_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordions', to='pipi.yourmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagefield',
            name='your_model',
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('accordion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pipi.accordion')),
            ],
        ),
    ]
