# Generated by Django 4.2 on 2024-10-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipi', '0008_accordion_remove_imagefield_your_model_accordionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefield',
            name='field_value',
        ),
        migrations.AddField(
            model_name='imagefield',
            name='your_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pipi.yourmodel'),
            preserve_default=False,
        ),
    ]
