# Generated by Django 4.2 on 2024-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipi', '0009_remove_imagefield_field_value_imagefield_your_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='field_value',
            field=models.TextField(),
        ),
    ]
